/*
    Function: PHTTP_fnc_Init

    Description:
        postInit entry point. Sets up the extension constants and the ExtensionCallback handler that
        receives asynchronous HTTP responses. When the extension signals that a response is ready it
        names a transaction id and a chunk count; this handler pulls the chunks back in order,
        reassembles the serialized hashmap, deletes the transaction, and runs the caller's callback.

    Globals defined:
        PHTTP_extension (STRING)  - extension name passed to callExtension.
        PHTTP_chunkSize (SCALAR)  - body chunk size used by fn_Request when sending.
        PHTTP_callbacks (HASHMAP) - pending callbacks keyed by transaction id.
*/

PHTTP_extension = "PhoenixHttp";
PHTTP_chunkSize = 7000;
PHTTP_callbacks = createHashMap;

addMissionEventHandler ["ExtensionCallback", {
    params ["_name", "_function", "_data"];
    if (_name isNotEqualTo PHTTP_extension || {_function isNotEqualTo "response"}) exitWith {};

    // _data is ["<id>", <chunkCount>].
    (parseSimpleArray _data) params ["_id", "_count"];

    private _raw = "";
    private _complete = true;

    // Pull each chunk. Every reply is "status:data"; split on the first colon only so chunk data
    // that contains colons (URLs, timestamps, IPv6, arbitrary JSON values) is reassembled intact.
    for "_index" from 0 to (_count - 1) do {
        private _reply = (PHTTP_extension callExtension ["request:get", [_id, _index]]) select 0;
        private _separator = _reply find ":";
        private _status = _reply select [0, _separator];
        if (_status isEqualTo "success") then {
            _raw = _raw + (_reply select [_separator + 1]);
        } else {
            _complete = false;
        };
    };

    PHTTP_extension callExtension ["request:delete", [_id]];

    private _callback = PHTTP_callbacks getOrDefault [_id, {}];
    PHTTP_callbacks deleteAt _id;

    // Only run the callback if every chunk arrived; the reassembled text is SQF that builds the
    // response hashmap (its structure is generated by the extension, its values are escaped).
    if (_complete && {_raw isNotEqualTo ""}) then {
        private _response = call compile _raw;
        [_response] call _callback;
    };
}];
